# Generated by Django 5.0.3 on 2024-03-13 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "videoid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("positive_count", models.CharField(max_length=100)),
                ("neutral_count", models.CharField(max_length=100)),
                ("negative_count", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
