# Generated by Django 5.0.3 on 2024-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment", "0002_remove_useractivity_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="model_chpice",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
