# Generated by Django 5.0.3 on 2024-04-06 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment", "0003_useractivity_model_chpice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useractivity",
            old_name="model_chpice",
            new_name="model_choice",
        ),
    ]
